---
spring:
  profiles: test
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:surveydb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    enabled: false
    url: jdbc:h2:mem:surveydb;DB_CLOSE_DELAY=-1
    user: sa
    password: password